font pango:JetBrainsMono Nerd Font 8

for_window [class=".*"] border pixel 1

# class                       borda     fundo        texto       indicador    borda_filho
client.focused              #FFFFFF #282A2E    #ffffff   #ffffff    #ffffff
client.background           #ffffff

gaps inner 3
gaps outer 3

