exec_always --no-startup-id ~/.config/polybar/launch.sh
exec_always --no-startup-id nitrogen --restore
exec_always --no-startup-id ~/scripts/default.sh
exec_always picom --config ~/.config/picom/picom.conf
exec --no-startup-id dex --autostart --environment i3
exec --no-startup-id xss-lock --transfer-sleep-lock -- i3lock --nofork
exec --no-startup-id nm-applet
exec --no-startup-id xfce4-power-manager
exec --no-startup-id xfsettingsd
