# ==============================================================================
# --- SISTEMA E APLICATIVOS ---
# ==============================================================================
bindsym $mod+Return exec alacritty
bindsym $mod+x exec rofi -show drun

bindsym $mod+Ctrl+s exec ~/scripts/rofi-mixer-menu.sh
bindsym $mod+Ctrl+w exec ~/scripts/rofi-wifi-menu.sh
bindsym $mod+Ctrl+b exec ~/scripts/rofi-bluetooth-menu.sh
bindsym $mod+Ctrl+period exec ~/scripts/screenshot.sh

bindsym $mod+t exec ~/scripts/tv.sh

bindsym XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +10% && $refresh_i3status
bindsym XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -10% && $refresh_i3status
bindsym XF86AudioMute exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle && $refresh_i3status
bindsym XF86AudioMicMute exec --no-startup-id pactl set-source-mute @DEFAULT_SOURCE@ toggle && $refresh_i3status

# ==============================================================================
# --- GERENCIAMENTO DE JANELAS ---
# ==============================================================================
bindsym $mod+a focus left
bindsym $mod+s focus down
bindsym $mod+w focus up
bindsym $mod+d focus right
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

bindsym $mod+Shift+a move left
bindsym $mod+Shift+s move down
bindsym $mod+Shift+w move up
bindsym $mod+Shift+d move right
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

bindsym $mod+q kill

bindsym $mod+h split h
bindsym $mod+v split v

bindsym $mod+f fullscreen toggle

bindsym $mod+space floating toggle
bindsym $mod+Shift+space focus mode_toggle

floating_modifier $mod
tiling_drag modifier titlebar

# ==============================================================================
# --- CONTROLE DO I3 ---
# ==============================================================================
bindsym $mod+c reload
bindsym $mod+r restart
bindsym $mod+e exec "i3-nagbar -t warning -m 'Você pressionou o atalho de saída. Tem certeza que deseja sair do i3? Isso encerrará sua sessão X.' -B 'Sim, sair do i3' 'i3-msg exit'"

